In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5911, 2127, 7074, 4794],
 [5911, 2127, 7074, 5533],
 [5911, 8532, 7074, 7028],
 [6594, 505, 4873, 2536, 1135],
 [6594, 505, 4873, 2536, 140],
 [6424, 5911, 8210, 7074, 4763],
 [5655, 6726, 1410, 2536]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential



In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5911 2127 7074 4794]
 [   0    0    0    0 5911 2127 7074 5533]
 [   0    0    0    0 5911 8532 7074 7028]
 [   0    0    0 6594  505 4873 2536 1135]
 [   0    0    0 6594  505 4873 2536  140]
 [   0    0    0 6424 5911 8210 7074 4763]
 [   0    0    0    0 5655 6726 1410 2536]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

d:\Valuebound-Training\projects\ml projects\myenv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step


array([[[-0.01301866,  0.01463134, -0.02022539, -0.0053599 ,
          0.00705007,  0.00553762, -0.03478366, -0.04400055,
          0.03616485, -0.0172495 ],
        [-0.01301866,  0.01463134, -0.02022539, -0.0053599 ,
          0.00705007,  0.00553762, -0.03478366, -0.04400055,
          0.03616485, -0.0172495 ],
        [-0.01301866,  0.01463134, -0.02022539, -0.0053599 ,
          0.00705007,  0.00553762, -0.03478366, -0.04400055,
          0.03616485, -0.0172495 ],
        [-0.01301866,  0.01463134, -0.02022539, -0.0053599 ,
          0.00705007,  0.00553762, -0.03478366, -0.04400055,
          0.03616485, -0.0172495 ],
        [-0.0127202 , -0.04176425,  0.0223076 , -0.02849486,
         -0.00318972,  0.00655519,  0.04784751,  0.03203143,
          0.02642563,  0.02357907],
        [ 0.03072998, -0.03535682, -0.04556483, -0.00459334,
         -0.02637869,  0.04190535, -0.03741286, -0.04026092,
         -0.03068143, -0.04029223],
        [-0.03858159,  0.01618958,  0.01512034, -0.0

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 5911, 2127, 7074, 4794])

In [19]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None